In [55]:
import pickle
import pandas as pd
import numpy as np
import os
import re

In [56]:
# Format:
# Bowler, batsman 
# Runs in numbers/words, out else 0. If wide/no ball then ignore entry
# out
def to_corrrect_format(filepath): 
    df = pd.read_csv(filepath, sep='delimiter',header=None, engine="python") #, names=["Players", "Outcome"]
    df = df[::-1]
    df.reset_index(drop=True, inplace=True)
    
    numbers_dict = {"zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6}
    data = []
    wkt_taken = 0
    num_over = 0
    prev_bowler = ''
    for index, row in df.iterrows():
        line = row.to_string(index=False)
        list = line.split(",")

        bowler, batsman = list[0].split(" to ")    
        if prev_bowler!=bowler: # what about case senstivity?
            prev_bowler=bowler
            num_over+=1

        if num_over>20:
            # print("Error")
            continue    

        find_runs = r'(zero|one|two|three|four|five|six|0|1|2|3|4|5|6)'
        find_extra = r'(wide|no ball)'
        outcome = re.findall(find_runs, list[1], flags=re.IGNORECASE)
        if re.findall("out", list[-1], flags=re.IGNORECASE):
            
            data.append([bowler, batsman, wkt_taken, num_over, 7])
            wkt_taken += 1
        elif outcome:
            # print(outcome)
            runs = 0
            if outcome[0].isdigit():
                runs = int(outcome[0])
            else:
                num = numbers_dict.get(outcome[0].lower(), None)
                if num is not None:
                    runs = num
            data.append([bowler, batsman, wkt_taken, num_over, runs])
        elif re.findall(find_extra, list[1], flags=re.IGNORECASE):
            continue
        else:
            data.append([bowler, batsman, wkt_taken, num_over, 0])
            # print("yay!")
        # print(list)
    # print(data)
    new_path = filepath.split(".")
    with open(new_path[0]+'.pkl', 'wb') as file:
        pickle.dump(data, file)

In [57]:
# current issues:
#   - Same player last names
#   - Dismissal on extras leads to >6 balls in an over
#   - counting byes as runs

In [40]:
# df = pd.read_csv("T20_matches/australia-vs-bangladesh-11th-match-group-a-412688/textsInnings1.csv", sep='delimiter',header=None) #, names=["Players", "Outcome"]
# df.head()

to_corrrect_format("T20_matches/australia-vs-bangladesh-11th-match-group-a-412688/textsInnings1.csv")

In [58]:
rootdir = 'T20_matches'
cnt=0
for subdir, dirs, files in os.walk(rootdir):
    # if(cnt>=10):
    #     break
    try: 
        for file in files:
            # if(cnt>=10):
            #     break
            if(file[-1]=='l'):
                continue
            to_corrrect_format(os.path.join(subdir, file))
            # cnt+=1
    except: 
        pass

In [ ]:
with open('D:/BTp/btp/T20_matches/australia-vs-bangladesh-11th-match-group-a-412688/textsInnings2.pkl', 'rb') as f:
    data = pickle.load(f)

In [68]:
df = pd.DataFrame(data)

In [69]:
df

0        1  2   3  4
0      Tait    Imrul  0   1  0
1      Tait    Imrul  0   1  0
2      Tait    Imrul  0   1  4
3      Tait    Imrul  0   1  0
4      Tait    Imrul  0   1  0
..      ...      ... ..  .. ..
107    Tait   Razzak  9  18  0
108  Harris  Mortaza  9  19  1
109  Harris   Razzak  9  19  2
110  Harris   Razzak  9  19  1
111  Harris  Mortaza  9  19  7

[112 rows x 5 columns]

In [59]:
data1=[]
rootdir = 'T20_matches'
# cnt=0
for subdir, dirs, files in os.walk(rootdir):
    # if(cnt>=20):
    #     break
    try: 
        for file in files:
            if(file[-1]=='v'):
                continue
            # if(cnt>=20):
            #     break
            print(os.path.join(subdir,file ))
            with open(os.path.join(subdir,file), 'rb') as f:
                data1+= (pickle.load(f))
            # cnt+=1
    except: 
        pass

T20_matches\australia-vs-bangladesh-11th-match-group-a-412688\textsInnings1.pkl
T20_matches\australia-vs-bangladesh-11th-match-group-a-412688\textsInnings2.pkl
T20_matches\australia-vs-bangladesh-14th-match-group-f-287866\textsInnings1.pkl
T20_matches\australia-vs-bangladesh-14th-match-group-f-287866\textsInnings2.pkl
T20_matches\australia-vs-england-1st-t20i-446960\textsInnings1.pkl
T20_matches\australia-vs-england-1st-t20i-446960\textsInnings2.pkl
T20_matches\australia-vs-england-2nd-t20i-446961\textsInnings1.pkl
T20_matches\australia-vs-england-2nd-t20i-446961\textsInnings2.pkl
T20_matches\australia-vs-england-9th-match-group-b-287861\textsInnings1.pkl
T20_matches\australia-vs-england-9th-match-group-b-287861\textsInnings2.pkl
T20_matches\australia-vs-england-final-412703\textsInnings1.pkl
T20_matches\australia-vs-england-final-412703\textsInnings2.pkl
T20_matches\australia-vs-england-only-t20i-249227\textsInnings1.pkl
T20_matches\australia-vs-england-only-t20i-249227\textsInnings2.

In [60]:
data1

[['Mortaza', 'Warner', 0, 1, 0],
 ['Mortaza', 'Warner', 0, 1, 0],
 ['Mortaza', 'Warner', 0, 1, 1],
 ['Mortaza', 'Watson', 0, 1, 0],
 ['Mortaza', 'Watson', 0, 1, 1],
 ['Mortaza', 'Warner', 0, 1, 0],
 ['Shafiul', 'Watson', 0, 2, 0],
 ['Shafiul', 'Watson', 0, 2, 1],
 ['Shafiul', 'Watson', 0, 2, 0],
 ['Shafiul', 'Watson', 0, 2, 2],
 ['Shafiul', 'Watson', 0, 2, 1],
 ['Shafiul', 'Warner', 0, 2, 6],
 ['Shafiul', 'Warner', 0, 2, 4],
 ['Mortaza', 'Watson', 0, 3, 7],
 ['Mortaza', 'Warner', 1, 3, 0],
 ['Mortaza', 'Warner', 1, 3, 4],
 ['Mortaza', 'Warner', 1, 3, 1],
 ['Mortaza', 'Clarke', 1, 3, 0],
 ['Mortaza', 'Clarke', 1, 3, 0],
 ['Shakib', 'Warner', 1, 4, 0],
 ['Shakib', 'Warner', 1, 4, 7],
 ['Shakib', 'Clarke', 2, 4, 0],
 ['Shakib', 'Clarke', 2, 4, 0],
 ['Shakib', 'Clarke', 2, 4, 0],
 ['Shakib', 'Clarke', 2, 4, 6],
 ['Razzak', 'Haddin', 2, 5, 0],
 ['Razzak', 'Haddin', 2, 5, 1],
 ['Razzak', 'Clarke', 2, 5, 0],
 ['Razzak', 'Clarke', 2, 5, 0],
 ['Razzak', 'Clarke', 2, 5, 1],
 ['Razzak', 'Haddin',

In [61]:
df1= pd.DataFrame(data1)

In [62]:
df1

0           1  2   3  4
0      Mortaza      Warner  0   1  0
1      Mortaza      Warner  0   1  0
2      Mortaza      Warner  0   1  1
3      Mortaza      Watson  0   1  0
4      Mortaza      Watson  0   1  1
...        ...         ... ..  .. ..
57637   Tanvir  Chigumbura  6  20  0
57638   Tanvir  Chigumbura  6  20  0
57639   Tanvir  Chigumbura  6  20  4
57640   Tanvir  Chigumbura  6  20  1
57641   Tanvir   Masakadza  6  20  0

[57642 rows x 5 columns]

In [63]:
df1=df1.rename(columns={0:"bowler",1:"batsman",2:"wicket",3:"over",4:"outcome"})

In [65]:
df1.columns

Index(['bowler', 'batsman', 'wicket', 'over', 'outcome'], dtype='object')

In [68]:
df1[df1['over']==21]

Empty DataFrame
Columns: [bowler, batsman, wicket, over, outcome]
Index: []

In [69]:
df1.to_pickle("./df1.pkl")

In [43]:
#seedha load df1 from df.pkl

In [44]:
np.where(df1['wicket']==10)

(array([], dtype=int64),)

In [70]:
batsmen_dict = {batsman: index for index, batsman in enumerate(df1['batsman'].unique())}
print("Dictionary of batsmen names:", batsmen_dict)

Dictionary of batsmen names: {'Warner': 0, 'Watson': 1, 'Clarke': 2, 'Haddin': 3, 'Hussey': 4, 'White': 5, 'Smith': 6, 'Harris': 7, 'Imrul': 8, 'Ashraful': 9, 'Shakib': 10, 'Aftab': 11, 'Mahmudullah': 12, 'Mushfiqur': 13, 'Md Naeem': 14, 'Jahurul': 15, 'Shafiul': 16, 'Mortaza': 17, 'Razzak': 18, 'Tamim': 19, 'Nazimuddin': 20, 'Kapali': 21, 'Farhad': 22, 'Gilchrist': 23, 'Hayden': 24, 'Ponting': 25, 'Finch': 26, 'Bell': 27, 'Davies': 28, 'Pietersen': 29, 'PD Collingwood': 30, 'Morgan': 31, 'Wright': 32, 'Bresnan': 33, 'Yardy': 34, 'Woakes': 35, 'Swann': 36, 'Shahzad': 37, 'Paine': 38, "O'Keefe": 39, 'Johnson': 40, 'Maddy': 41, 'Prior': 42, 'Flintoff': 43, 'Shah': 44, 'AD Mascarenhas': 45, 'Schofield': 46, 'Broad': 47, 'Kirtley': 48, 'Symonds': 49, 'Lumb': 50, 'Kieswetter': 51, 'Joyce': 52, 'Vaughan': 53, 'Nixon': 54, 'Dalrymple': 55, 'Lewis': 56, 'Panesar': 57, 'Anderson': 58, 'Vijay': 59, 'Gambhir': 60, 'Raina': 61, 'Rohit Sharma': 62, 'Yuvraj': 63, 'Dhoni': 64, 'Pathan': 65, 'Jadeja':

In [71]:
# Create the four-dimensional matrix X
num_batsmen = len(batsmen_dict)
max_over = 20  # Adding 1 to account for zero-based indexing
max_wicket = 10 
max_outcome = 8

X = np.zeros((num_batsmen, max_over, max_wicket, max_outcome), dtype=int)

# Populate the matrix X based on DataFrame values
for index, row in df1.iterrows():
    batsman_idx = batsmen_dict[row['batsman']]
    over_idx = row['over']-1
    wicket_idx = row['wicket']
    outcome_idx = row['outcome']
    
    X[batsman_idx, over_idx, wicket_idx, outcome_idx] += 1

print("Four-dimensional matrix X:")
print(X)

Four-dimensional matrix X:
[[[[65 35  8 ...  0  4  5]
   [ 0  1  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[39 28  5 ...  0  5  4]
   [ 8  4  0 ...  0  0  0]
   [ 5  1  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[21 18  7 ...  0  6  5]
   [ 7  5  1 ...  0  0  0]
   [ 5  1  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  ...

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0 

In [72]:
X[batsmen_dict['Kohli']][14][2]

array([2, 4, 0, 0, 0, 0, 0, 1])

In [18]:
np.save("X_mat.npy", X)