In [2]:
import pickle
import pandas as pd
import numpy as np
import os
import re

In [56]:
# Format:
# Bowler, batsman 
# Runs in numbers/words, out else 0. If wide/no ball then ignore entry
# out
def to_corrrect_format(filepath): 
    df = pd.read_csv(filepath, sep='delimiter',header=None, engine="python") #, names=["Players", "Outcome"]
    df = df[::-1]
    df.reset_index(drop=True, inplace=True)
    
    numbers_dict = {"zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6}
    data = []
    wkt_taken = 0
    num_over = 0
    prev_bowler = ''
    for index, row in df.iterrows():
        line = row.to_string(index=False)
        list = line.split(",")

        bowler, batsman = list[0].split(" to ")    
        if prev_bowler!=bowler: # what about case senstivity?
            prev_bowler=bowler
            num_over+=1

        if num_over>20:
            # print("Error")
            continue    

        find_runs = r'(zero|one|two|three|four|five|six|0|1|2|3|4|5|6)'
        find_extra = r'(wide|no ball)'
        outcome = re.findall(find_runs, list[1], flags=re.IGNORECASE)
        if re.findall("out", list[-1], flags=re.IGNORECASE):
            
            data.append([bowler, batsman, wkt_taken, num_over, 7])
            wkt_taken += 1
        elif outcome:
            # print(outcome)
            runs = 0
            if outcome[0].isdigit():
                runs = int(outcome[0])
            else:
                num = numbers_dict.get(outcome[0].lower(), None)
                if num is not None:
                    runs = num
            data.append([bowler, batsman, wkt_taken, num_over, runs])
        elif re.findall(find_extra, list[1], flags=re.IGNORECASE):
            continue
        else:
            data.append([bowler, batsman, wkt_taken, num_over, 0])
            # print("yay!")
        # print(list)
    # print(data)
    new_path = filepath.split(".")
    with open(new_path[0]+'.pkl', 'wb') as file:
        pickle.dump(data, file)

In [57]:
# current issues:
#   - Same player last names
#   - Dismissal on extras leads to >6 balls in an over
#   - counting byes as runs

In [40]:
# df = pd.read_csv("T20_matches/australia-vs-bangladesh-11th-match-group-a-412688/textsInnings1.csv", sep='delimiter',header=None) #, names=["Players", "Outcome"]
# df.head()

to_corrrect_format("T20_matches/australia-vs-bangladesh-11th-match-group-a-412688/textsInnings1.csv")

In [3]:
rootdir = 'T20_matches'
cnt=0
for subdir, dirs, files in os.walk(rootdir):
    # if(cnt>=10):
    #     break
    try: 
        for file in files:
            # if(cnt>=10):
            #     break
            if(file[-1]=='l'):
                continue
            to_corrrect_format(os.path.join(subdir, file))
            # cnt+=1
    except: 
        pass

In [ ]:
with open('D:/BTp/btp/T20_matches/australia-vs-bangladesh-11th-match-group-a-412688/textsInnings2.pkl', 'rb') as f:
    data = pickle.load(f)

In [68]:
df = pd.DataFrame(data)

In [69]:
df

0        1  2   3  4
0      Tait    Imrul  0   1  0
1      Tait    Imrul  0   1  0
2      Tait    Imrul  0   1  4
3      Tait    Imrul  0   1  0
4      Tait    Imrul  0   1  0
..      ...      ... ..  .. ..
107    Tait   Razzak  9  18  0
108  Harris  Mortaza  9  19  1
109  Harris   Razzak  9  19  2
110  Harris   Razzak  9  19  1
111  Harris  Mortaza  9  19  7

[112 rows x 5 columns]

In [34]:
data1=[]
rootdir = 'T20_matches'
# cnt=0
for subdir, dirs, files in os.walk(rootdir):
    # if(cnt>=20):
    #     break
    try: 
        for file in files:
            if(file[-1]=='v'):
                continue
            # if(cnt>=20):
            #     break
            if file.endswith('1.pkl'):
                print(os.path.join(subdir,file ))
                with open(os.path.join(subdir,file), 'rb') as f:
                    data1+= (pickle.load(f))
            # cnt+=1
    except: 
        pass

T20_matches\australia-vs-bangladesh-11th-match-group-a-412688\textsInnings1.pkl
T20_matches\australia-vs-bangladesh-14th-match-group-f-287866\textsInnings1.pkl
T20_matches\australia-vs-england-1st-t20i-446960\textsInnings1.pkl
T20_matches\australia-vs-england-2nd-t20i-446961\textsInnings1.pkl
T20_matches\australia-vs-england-9th-match-group-b-287861\textsInnings1.pkl
T20_matches\australia-vs-england-final-412703\textsInnings1.pkl
T20_matches\australia-vs-england-only-t20i-249227\textsInnings1.pkl
T20_matches\australia-vs-india-15th-match-group-f-412691\textsInnings1.pkl
T20_matches\australia-vs-india-16th-match-group-2-533287\textsInnings1.pkl
T20_matches\australia-vs-india-1st-t20i-518954\textsInnings1.pkl
T20_matches\australia-vs-india-2nd-semi-final-287878\textsInnings1.pkl
T20_matches\australia-vs-india-2nd-t20i-518955\textsInnings1.pkl
T20_matches\australia-vs-india-only-t20i-291356\textsInnings1.pkl
T20_matches\australia-vs-new-zealand-only-t20i-291343\textsInnings1.pkl
T20_match

In [35]:
data1

[['Mortaza', 'Warner', 0, 1, 0],
 ['Mortaza', 'Warner', 0, 1, 0],
 ['Mortaza', 'Warner', 0, 1, 1],
 ['Mortaza', 'Watson', 0, 1, 0],
 ['Mortaza', 'Watson', 0, 1, 1],
 ['Mortaza', 'Warner', 0, 1, 0],
 ['Shafiul', 'Watson', 0, 2, 0],
 ['Shafiul', 'Watson', 0, 2, 1],
 ['Shafiul', 'Watson', 0, 2, 0],
 ['Shafiul', 'Watson', 0, 2, 2],
 ['Shafiul', 'Watson', 0, 2, 1],
 ['Shafiul', 'Warner', 0, 2, 6],
 ['Shafiul', 'Warner', 0, 2, 4],
 ['Mortaza', 'Watson', 0, 3, 7],
 ['Mortaza', 'Warner', 1, 3, 0],
 ['Mortaza', 'Warner', 1, 3, 4],
 ['Mortaza', 'Warner', 1, 3, 1],
 ['Mortaza', 'Clarke', 1, 3, 0],
 ['Mortaza', 'Clarke', 1, 3, 0],
 ['Shakib', 'Warner', 1, 4, 0],
 ['Shakib', 'Warner', 1, 4, 7],
 ['Shakib', 'Clarke', 2, 4, 0],
 ['Shakib', 'Clarke', 2, 4, 0],
 ['Shakib', 'Clarke', 2, 4, 0],
 ['Shakib', 'Clarke', 2, 4, 6],
 ['Razzak', 'Haddin', 2, 5, 0],
 ['Razzak', 'Haddin', 2, 5, 1],
 ['Razzak', 'Clarke', 2, 5, 0],
 ['Razzak', 'Clarke', 2, 5, 0],
 ['Razzak', 'Clarke', 2, 5, 1],
 ['Razzak', 'Haddin',

In [36]:
df1= pd.DataFrame(data1)

In [37]:
df1

0        1  2   3  4
0      Mortaza   Warner  0   1  0
1      Mortaza   Warner  0   1  0
2      Mortaza   Warner  0   1  1
3      Mortaza   Watson  0   1  0
4      Mortaza   Watson  0   1  1
...        ...      ... ..  .. ..
30546   Vitori  Shehzad  1  20  2
30547   Vitori  Shehzad  1  20  2
30548   Vitori  Shehzad  1  20  1
30549   Vitori   Hafeez  1  20  1
30550   Vitori  Shehzad  1  20  1

[30551 rows x 5 columns]

In [38]:
df1=df1.rename(columns={0:"bowler",1:"batsman",2:"wicket",3:"over",4:"outcome"})

In [39]:
df1.columns

Index(['bowler', 'batsman', 'wicket', 'over', 'outcome'], dtype='object')

In [40]:
df1[df1['over']==21]

Empty DataFrame
Columns: [bowler, batsman, wicket, over, outcome]
Index: []

In [41]:
df1.to_pickle("./df1.pkl")

In [42]:
#seedha load df1 from df.pkl

In [43]:
np.where(df1['wicket']==10)

(array([], dtype=int64),)

In [44]:
batsmen_dict = {batsman: index for index, batsman in enumerate(df1['batsman'].unique())}
print("Dictionary of batsmen names:", batsmen_dict)

Dictionary of batsmen names: {'Warner': 0, 'Watson': 1, 'Clarke': 2, 'Haddin': 3, 'Hussey': 4, 'White': 5, 'Smith': 6, 'Harris': 7, 'Tamim': 8, 'Nazimuddin': 9, 'Aftab': 10, 'Ashraful': 11, 'Shakib': 12, 'Mortaza': 13, 'Kapali': 14, 'Farhad': 15, 'Mushfiqur': 16, 'Finch': 17, 'Paine': 18, "O'Keefe": 19, 'Johnson': 20, 'Maddy': 21, 'Prior': 22, 'Wright': 23, 'Pietersen': 24, 'PD Collingwood': 25, 'Flintoff': 26, 'Shah': 27, 'AD Mascarenhas': 28, 'Schofield': 29, 'Broad': 30, 'Kirtley': 31, 'Gilchrist': 32, 'Hayden': 33, 'Ponting': 34, 'Symonds': 35, 'Gambhir': 36, 'Pathan': 37, 'Kohli': 38, 'Yuvraj': 39, 'Rohit Sharma': 40, 'Dhoni': 41, 'Raina': 42, 'Ashwin': 43, 'Harbhajan': 44, 'Wade': 45, 'Birt': 46, 'Bailey': 47, 'Sehwag': 48, 'Uthappa': 49, 'Marsh': 50, 'Lee': 51, 'McKay': 52, 'Hogg': 53, 'Doherty': 54, 'Karthik': 55, 'Praveen': 56, 'Sreesanth': 57, 'Sharma': 58, 'Voges': 59, 'Pomersbach': 60, 'Ferguson': 61, 'Hopes': 62, 'Henriques': 63, 'Siddle': 64, 'Hodge': 65, 'Maxwell': 66, '

In [45]:
# Create the four-dimensional matrix X
num_batsmen = len(batsmen_dict)
max_over = 20 
max_wicket = 10 
max_outcome = 8

X = np.zeros((num_batsmen, max_over, max_wicket, max_outcome), dtype=int)

# Populate the matrix X based on DataFrame values
for index, row in df1.iterrows():
    batsman_idx = batsmen_dict[row['batsman']]
    over_idx = row['over']-1
    wicket_idx = row['wicket']
    outcome_idx = row['outcome']
    
    X[batsman_idx, over_idx, wicket_idx, outcome_idx] += 1

print("Four-dimensional matrix X:")
print(X)

Four-dimensional matrix X:
[[[[41 20  6 ...  0  0  1]
   [ 0  1  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[23 18  3 ...  0  2  3]
   [ 2  3  0 ...  0  0  0]
   [ 5  1  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 7 10  4 ...  0  4  2]
   [ 3  5  1 ...  0  0  0]
   [ 5  1  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  ...

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0 

In [46]:
X[batsmen_dict['Kohli']][14][2]

array([2, 2, 0, 0, 0, 0, 0, 1])

In [47]:
np.save("X_mat.npy", X)

: 